@url = http://localhost:3060/v1/api/
# @url = http://localhost:8080/v1/api/

### signup
POST {{url}}shop/signup
Content-Type: application/json
x-api-key:97bb76d929bafead000c14308df98e9aea30d09ebab5be6dfe3621d040ccb7e3ddfde7afd03dfe103db328e6b7c91817aebff9b40562c296364d4c7d20adbed0

{
    "name":"Shop 3",
    "email":"shop@example78.com",
    "password":"abc123"
}


### login
POST {{url}}shop/login
Content-Type: application/json
x-api-key:97bb76d929bafead000c14308df98e9aea30d09ebab5be6dfe3621d040ccb7e3ddfde7afd03dfe103db328e6b7c91817aebff9b40562c296364d4c7d20adbed0

{
    "email":"shop@example78.com",
    "password":"abc123"
}